# This is the main ansible-playbook

# Run using:
# ansible-playbook site.yml -i environments/vm/inventory

## Ansible version requirements:
##  2.2 : provide include_role plugin
- name: Check Ansible version
  hosts: all
  remote_user: "{{ ansible_remote_user }}"
  tags: check_ansible
  tasks:
    - name: Check Ansible version
      assert:
        that: "ansible_version.full is version_compare('2.5.0', '>=')"
        msg: "This playbook requires Ansible 2.5.0 or greater."

- name: Get Jinja2 version
  hosts: all
  gather_facts: no
  remote_user: "{{ ansible_remote_user }}"
  tags: check_jinja2
  tasks:
    - action: jin_ver
      register: jinja_version

- name: Check Jinja2 version
  hosts: all
  remote_user: "{{ ansible_remote_user }}"
  tags: check_jinja2
  tasks:
    - name: Check Jinja2 version
      assert:
        that: "jinja_version.version_value is version_compare('2.10', '>=')"
        msg: "This playbook requires Jinja2 2.10 or greater. You have {{ jinja_version.version_value }}."

- name: Apply roles to appropriate nodes
  hosts: all
  become: yes
  remote_user: "{{ ansible_remote_user }}"
  roles:
    - role: common
      tags:
        - common
    - role: sympa
      tags:
        - sympa
      when: "'sympa' in group_names"

