# Vagrant configuration file for a development VM
# Works with vmware fusion and virtual box providers

Vagrant.configure("2") do |config|
    # VM images to use
    boxes = [
        { :name => "local-sympa", :box => "puppetlabs/ubuntu-16.04-64-nocm" }
    ]

    boxes.each do |opts|
      config.vm.define opts[:name] do |conf|
        conf.vm.box = opts[:box]
        # Give it a fixed IP
        conf.vm.network "private_network", ip: "192.168.66.67", :netmask => "255.255.255.0"
        conf.vm.provider "vmware_fusion" do |v|
            v.vmx["memsize"] = "1024"
        end
        conf.vm.provider "virtualbox" do |v|
            v.memory = 1024
        end
      end
    end

#    # VM: "dev-vm2"
#    config.vm.define "dev-vm2" do |conf|
#        conf.vm.hostname = "dev-vm2"
#        # Give it a fixed IP
#        conf.vm.network "private_network", ip: "192.168.66.67", :netmask => "255.255.255.0"
#        conf.vm.provider "vmware_fusion" do |v|
#            v.vmx["memsize"] = "1024"
#        end
#        conf.vm.provider "virtualbox" do |v|
#            v.memory = 1024
#        end
#    end

    config.vm.provision "ansible" do |ansible|
        # Groups to add to the Ansible inventory file generated by Vagrant
        # For use by ansible-playbook later.
        # These are not used by provision.yml

        ansible.groups = {
          "sympa" => ["local-sympa"],
          "apache" => ["local-sympa"],
          "postfix" => ["local-sympa"],
        }
        ansible.playbook = "create_inventory.yml"
        ansible.limit="all"
        ansible.inventory_path="environments/setup.ini"
        #ansible.verbose = "vvvv" # For troubleshooting ansible connection problems
    end

end
