---

- name: Ensures git is installed.
  apt:
    name: git
    state: present

- name: Download sources from repository
  git:
    repo: "{{ sympa.repository }}"
    dest: "{{ install_prefix }}/{{ sympa.install_dir_name }}/src/{{ source_dir }}"
    force: yes
    version: "{{ sympa.repository_version }}"

- name: Prepare configure
  command: autoreconf -i
  args:
    chdir: "{{ install_prefix }}/{{ sympa.install_dir_name }}/src/{{ source_dir }}"

