---

- name: Upgrade Sympa
  command: "{{ install_prefix }}/{{ sympa.install_dir_name }}/bin/sympa.pl --upgrade"
  when: sympa.installation_method != 'package'

- name: Create Sympa database for new installations
  command: "{{ install_prefix }}/{{ sympa.install_dir_name }}/bin/sympa.pl --health_check"
  when: sympa.installation_method != 'package'

- name: Create systemd directory for custom conf
  file: dest=/etc/systemd/system/sympa.service.d state=directory mode=755

- name: Install custom systemd conf to define requirements with mysql server  
  template: src=systemd/custom.conf.j2 dest=/etc/systemd/system/sympa.service.d/custom.conf mode=0644

- name: Start Sympa via systemd
  systemd:
    enabled: yes
    state: restarted
    name: sympa
    daemon_reload: yes
