---
# Configure Apache

- name: Install Apache2
  apt: name={{ item }} state=present
  with_items:
  - apache2
  - libapache2-mod-fcgid # FastCGI interface module for Apache 2

- name: Enable CGI Apache module
  apache2_module: name=fcgid state=present
  notify: restart webserver
  tags: apache
 
- name: install custom fcgid.conf file
  template: src=apache/fcgid.conf.j2 dest=/etc/apache2/mods-available/fcgid.conf
  notify: restart webserver
  tags: apache
