---

- name: Installing Apache2
  apt:
    name: 
      - apache2
      - libapache2-mod-fcgid
      - spawn-fcgi
    state: present
  tags: apache

- name: install wwsympa service config
  template: src=fcgi/wwsympa.service.j2 dest=/lib/systemd/system/wwsympa.service
  tags: apache

- name: start wwsympa
  systemd:
    state: started
    name: wwsympa
    enabled: yes
    daemon_reload: yes
  tags: apache

- name: Run FCGI role
  import_role:
    name: sympa-fcgi
  tags: apache

- name: Install Sympa web config
  template: src=apache/sympa_web.conf.j2 dest=/etc/apache2/conf-available/sympa.conf
  notify: Restart Apache
  tags: apache

- name: Enable mod_rewrite
  command: a2enmod proxy_fcgi
  notify: Restart Apache

- name: Enable Sympa web config
  command: a2enconf sympa
  notify: Restart Apache

- name: Enable mod_rewrite
  command: a2enmod rewrite
  notify: Restart Apache

- name: Add redirect from / to /sympa
  tags: apache
  blockinfile:
    state: present
    marker: "# {mark} ANSIBLE MANAGED {{ item }} redirect to /sympa"
    path: "/etc/apache2/sites-available/{{ item }}.conf"
    block: |
      RewriteEngine On
      RewriteRule ^/?$ https://%{SERVER_NAME}/sympa [QSA,R=301,L]
  notify: Restart Apache
  with_items: "{{ web_domains }}"

