---
- name: Service unit file for {{ unit_name }}
  template:
    src: service.j2
    dest: "{{ systemd.unit_directory }}//{{ unit_name }}@.service"
  tags:
    - sympa-fcgi

- name: Socket unit file for {{ unit_name }}
  template:
    src: socket.j2
    dest: "{{ systemd.unit_directory }}/{{ unit_name }}@.socket"

- name: Enable and start {{ unit_name }} sockets
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "{{ unit_name}}@{{ item }}.socket"
  loop: "{{ range(1, vars['sympa']['web'][unit_name + '_procs'] + 1) | list }}"

- name: Enable and start {{ unit_name }} services
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "{{ unit_name }}@{{ item }}.service"
  loop: "{{ range(1, vars['sympa']['web'][unit_name + '_procs'] + 1) | list }}"
